### ISSUE TITLE
Anchor Text for msmarco-document and msmarco-document-v2

### ISSUE THREAD

**Issue by mam10eks** [allenai/ir_datasets#154]
**Dataset Information:**

We have extracted anchor text pointing to documents in MS MARCO (version 1 and version 2) from several Common Crawl snapshots that can be used as additional retrieval features or for the training of models (e.g., in a distant supervision style like DeepCT).

**Links to Resources:**

- [Code and links to the data](https://github.com/webis-de/ecir22-anchor-text)
- [Paper](https://webis.de/publications.html?q=Anchor#froebe_2022a)

**Dataset ID(s) & supported entities:**

 - Dataset ID: `msmarco-document/anchor-text` and `msmarco-document-v2/anchor-text`

**Checklist**

Mark each task once completed. All should be checked prior to merging a new dataset.
  
 - [x] Dataset definition (in `ir_datasets/datasets/[topid].py`)
 - [x] Tests (in `tests/integration/[topid].py`)
 - [ ] Metadata generated (using `ir_datasets generate_metadata` command, should appear in `ir_datasets/etc/metadata.json`)
 - [x] Documentation (in `ir_datasets/etc/[topid].yaml`)
   - [ ] Documentation generated in https://github.com/seanmacavaney/ir-datasets.com/
 - [x] Downloadable content (in `ir_datasets/etc/downloads.json`)
   - [x] Download verification action (in `.github/workflows/verify_downloads.yml`). Only one needed per `topid`.
   - [x] Any small public files from NIST (or other potentially troublesome files) mirrored in https://github.com/seanmacavaney/irds-mirror/. Mirrored status properly reflected in `downloads.json`.
  
**Additional comments/concerns/ideas/etc.**

I would be happy to help integrate the anchor texts into `ir_datasets`. I am not sure what a good Dataset ID would be, it can make sense to integrate it as a subset into the existing `msmarco-document` and `msmarco-document-v2` Ids but it might also make sense to have it as independent Ids.

**Comment by mam10eks** [comment]
It looks like I have the basic integration working. In the current version, the anchor texts pointing to a document are concatenated to produce the text of a GenericDoc. I think it might also be helpful to build a second representation where a document has a list of anchors (i.e., not concatenating them) because this might be helpful for training models like DeepCT.

**Comment by mam10eks** [comment]
Thanks @seanmacavaney for the feedback!

I have changed the implementation accordingly so that the anchor-text-documents now provide the `doc_id`, `text`, and `anchors`.

The main parts are done, but two things are still missing:
- I have not generated the Metadata because it looks like this needs to download all other datasets as well
- I was able to generate the Documentation, but I had to change a small thing in the [associated script](https://github.com/seanmacavaney/ir-datasets.com/blob/master/generate.py#L339) since otherwise the script failed for some Optional datatypes from other datasets and I would not like to push my changes in the script since they are only a workaround. But I checked that the generated documentation for the anchor-text looks like expected:
![Screenshot_20220119_083055](https://user-images.githubusercontent.com/10050886/150087148-f69a2c59-7abd-4955-b3bb-2d5fd1c3db9f.png)

Would it be ok when we merge the current state and you can  help with the generation of the metadata and documentation?

**Comment by seanmacavaney** [comment]
Awesome, thanks 🤘! This looks great. I opened a PR for this, and I'll take care of the metadata and documentation.

**Comment by mam10eks** [comment]
Nice, thanks! Please let me know when I can help further (I already saw that the automated checks failed, but this seems to be caused by the missing metadata).

**Comment by seanmacavaney** [comment]
@mam10eks -- can you accept the PR here with the metadata when you get a chance? https://github.com/mam10eks/ir_datasets/pull/1

**Comment by seanmacavaney** [comment]
Excellent, thanks again @mam10eks!
