### ISSUE TITLE
A question about WikiIR dataset

### ISSUE THREAD

**Issue by TheTahaaa** [allenai/ir_datasets#227]
**Dataset(s)**
[WikiIR dataset](https://ir-datasets.com/wikir.html)

**Describe the proposed change**
Hey there, I was working with the WikiIR dataset and found it a bit confusing. I don't understand why the pairs of (query, document) are different in _qrels_ and _scoredocs_ files. In the beginning, I thought the _scoredocs_ file contains the relevancy score of each sample in _qrels_, but seems that's not the case. The pairs of (query, document) are almost completely different in these two files!
Maybe a bit more clarification for these two files help people like me to understand it and don't get confused.

Thanks a bunch!

**Comment by seanmacavaney** [comment]
`qrels` are the relevance assessments. Usually these are from human assessments, but the case of WikIR, they are inferred as follows:

![Screen Shot 2023-03-25 at 13 23 39](https://user-images.githubusercontent.com/2607830/227719802-9e73492e-8b1c-4d7a-a7b9-652d7ba67840.png)

`scoreddocs` is a sample ranking of documents from a search engine. This is often used in "re-ranking" subtasks, to ensure that different re-ranking systems start with the same initial set of documents. In the case of WikIR, I believe the authors release their BM25 run for this purpose. The scores in `scoreddocs` are the score from the retrieval engine (if available).

If you're building a system that performs retrieval, it's safe to ignore `scoreddocs`; they are only useful when doing controlled re-ranking experiments.

Does this help?

**Comment by TheTahaaa** [comment]
> `qrels` are the relevance assessments. Usually these are from human assessments, but the case of WikIR, they are inferred as follows:
> 
> ![Screen Shot 2023-03-25 at 13 23 39](https://user-images.githubusercontent.com/2607830/227719802-9e73492e-8b1c-4d7a-a7b9-652d7ba67840.png)
> 
> `scoreddocs` is a sample ranking of documents from a search engine. This is often used in "re-ranking" subtasks, to ensure that different re-ranking systems start with the same initial set of documents. In the case of WikIR, I believe the authors release their BM25 run for this purpose. The scores in `scoreddocs` are the score from the retrieval engine (if available).
> 
> If you're building a system that performs retrieval, it's safe to ignore `scoreddocs`; they are only useful when doing controlled re-ranking experiments.
> 
> Does this help?

Certainly! I appreciate your assistance.

**Comment by seanmacavaney** [comment]
No problem!
