### ISSUE TITLE
Switch from namedtuple to dataclasses

### ISSUE THREAD

**Issue by bpiwowar** [allenai/ir_datasets#240]
**Is your feature request related to a problem? Please describe.**
Libraries relying using ir_datasets might need to include extra information into the data objects (e.g. GenericDoc). NamedTuple prevents any inheritence.

**Describe the solution you'd like**
Switch to dataclasses

**Describe alternatives you've considered**
No real alternative apart from trying to use ugly Python constructions or wrappers (but those are not really nice).

**Comment by seanmacavaney** [comment]
Hey Benjamin! We've got the reasoning for `namedtuple` over `dataclass` detailed here: https://ir-datasets.com/design.

I understand that NamedTuples are not very conducive to inheritance, but I don't think inheritance adds very much in most cases, and it doesn't seem worth it above the considerations detailed in the link. Can you give some specific case where you'd find inheritance of the fields helpful?

**Comment by bpiwowar** [comment]
Hi, sorry I did not see this page; OK, this makes sense even though slotted dataclasses should be quite close performance-wise in recent python versions. Maybe to be reconsidered in the future?

**Comment by seanmacavaney** [comment]
I'm potentially open to it!

**Comment by bpiwowar** [comment]
BTW, in the potential use cases:

- factorize some common properties (so that libraries can decide with `isinstance` what to do with one object)
- allow adding some extra information (e.g. an internal document ID)

**Comment by bpiwowar** [comment]
Also, a good alternative would be attrs, see e.g. for a full comparison

https://towardsdatascience.com/battle-of-the-data-containers-which-python-typed-structure-is-the-best-6d28fde824e
