### ISSUE TITLE
PyTorch Usability / Process-Safety

### ISSUE THREAD

**Issue by jacobdanovitch** [allenai/ir_datasets#25]
Hey,

Thanks for putting this together, this is a super useful resource. I was wondering if the datasets were intended to be interoperable with pytorch - a use case might be for building an embedding index, for example, where you'd want to load everything into a `DataLoader` and then iterate over them. 

I tried to do this using an `IterableDataset`, but it appears not to be process safe, leading to examples being duplicated. MWE: 

```python
import itertools

import ir_datasets
from torch.utils.data import (
    IterableDataset, 
    DataLoader, 
    get_worker_info
)

class IRDataset(IterableDataset):
    def __init__(
        self, 
        dataset: str
    ):
        self.dataset = ir_datasets.load(dataset) 

    def __iter__(self):
        worker_id = getattr(get_worker_info(), 'id', -1)
        for doc in self.dataset.docs_iter():
            yield doc.doc_id, worker_id

if __name__ == '__main__':
    loader = DataLoader(
        IRDataset('msmarco-passage/dev'),
        batch_size=8, 
        num_workers=2
    )

    for ids, worker_id in itertools.islice(loader, 10):
        print(ids, worker_id)
```

This prints:

```
('0', '1', '2', '3', '4', '5', '6', '7') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('0', '1', '2', '3', '4', '5', '6', '7') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('8', '9', '10', '11', '12', '13', '14', '15') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('8', '9', '10', '11', '12', '13', '14', '15') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('16', '17', '18', '19', '20', '21', '22', '23') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('16', '17', '18', '19', '20', '21', '22', '23') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('24', '25', '26', '27', '28', '29', '30', '31') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('24', '25', '26', '27', '28', '29', '30', '31') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('32', '33', '34', '35', '36', '37', '38', '39') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('32', '33', '34', '35', '36', '37', '38', '39') tensor([1, 1, 1, 1, 1, 1, 1, 1])
```

The data is duplicated on each worker. I was able to fix it by using a multiprocessing queue and a couple of other utilities, but I'm not sure if I'm going beyond the intended scope of the project here. I can definitely see why/how this would happen.

Thanks again for the work on this.

**Comment by seanmacavaney** [comment]
Hi Jakob,

I have not personally used pytorch's IterableDataset before, but [based on the documentation](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset) it seems that it's up to the defined `__iter__` function to choose how to split up the records for each worker.

Probably the simplest way to do this is with islice (providing start=worker_id and step=num_workers). Here's a fully workable example:

```
import itertools

import ir_datasets
from torch.utils.data import (
    IterableDataset, 
    DataLoader, 
    get_worker_info
)

class IRDataset(IterableDataset):
    def __init__(
        self, 
        dataset: str
    ):
        self.dataset = ir_datasets.load(dataset) 

    def __iter__(self):
        worker_info = get_worker_info()
        worker_id = getattr(worker_info, 'id', -1)
        docs_iter = self.dataset.docs_iter()
        if worker_id != -1:
            docs_iter = itertools.islice(docs_iter, worker_id, None, worker_info.num_workers)
        for doc in docs_iter:
            yield doc.doc_id, worker_id

if __name__ == '__main__':
    loader = DataLoader(
        IRDataset('msmarco-passage/dev'),
        batch_size=8, 
        num_workers=2
    )

    for ids, worker_id in itertools.islice(loader, 10):
        print(ids, worker_id)
```

Which prints:

```
('0', '2', '4', '6', '8', '10', '12', '14') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('1', '3', '5', '7', '9', '11', '13', '15') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('16', '18', '20', '22', '24', '26', '28', '30') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('17', '19', '21', '23', '25', '27', '29', '31') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('32', '34', '36', '38', '40', '42', '44', '46') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('33', '35', '37', '39', '41', '43', '45', '47') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('48', '50', '52', '54', '56', '58', '60', '62') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('49', '51', '53', '55', '57', '59', '61', '63') tensor([1, 1, 1, 1, 1, 1, 1, 1])
('64', '66', '68', '70', '72', '74', '76', '78') tensor([0, 0, 0, 0, 0, 0, 0, 0])
('65', '67', '69', '71', '73', '75', '77', '79') tensor([1, 1, 1, 1, 1, 1, 1, 1])
```

Does this meet your needs?

**Comment by seanmacavaney** [comment]
Now- in terms of efficiency, using islice isn't ideal. It means that the entire source file is read by all the workers. For a collection like MSMARCO, which you use here, it's not that big of a deal because it's small and the cost of processing each document is low. But for larger collections, this could be really costly (think: ClueWeb).

One way to work around this is to provide start/stop as part of the ir_datasets API. Then, the call could look something like this:
```
docs_per_worker = self.dataset.docs_count() // worker_info.num_workers # need to add docs_count
start = docs_per_worker * worker_id
stop = docs_per_worker * (worker_id + 1)
for doc in self.dataset.docs_iter(start, stop): # the implementations would need to know how to skip to a document at an arbitrary position
   ...
```
(I may have an off-by-one error in there, but just to give an idea.)

This would require adding `dataset.doc_count()`and start/stop arguments for `dataset.docs_iter()` -- which require special handling for each type of data source. I could see this being a useful enhancement, though. What do you think?

-----

An alternative would be to provide an iterator of document IDs (hopefully this could be really cheap), and then use those IDs to look up the required documents in the `docs_store()`. That wouldn't be as efficient or as clear though, IMO.

**Comment by seanmacavaney** [comment]
@jacobdanovitch did the islice approach above solve your problem? I went ahead and split off fancier slicing stuff into a new issue (#26) because it seemed to go beyond the scope of your particular problem.

**Comment by jacobdanovitch** [comment]
Nice! That's a lot cleaner than my queue solution. If you want to keep the worker info stuff out of `__iter__`, you can equivalently do this:

```python
class IRDataset(IterableDataset):
    # same as above

    def __iter__(self):
        docs_iter = self.dataset.docs_iter()
        if hasattr(self, 'data_slice'):
            docs_iter = itertools.islice(docs_iter, *self.data_slice)

        for doc in docs_iter:
            yield doc.doc_id

    @staticmethod
    def worker_init_fn(worker_id):
        worker_info = get_worker_info()
        dataset = worker_info.dataset
        dataset.data_slice = (worker_info.id, None, worker_info.num_workers)

dataset = IRDataset('msmarco-passage/dev')
data_loader = DataLoader(
    dataset,
    batch_size=..., 
    num_workers=..., 
    worker_init_fn=IRDataset.worker_init_fn
)
```

I'll provide my thoughts on a `dataset.docs_iter()`/ id iterator in the new issue thread.
