### ISSUE TITLE
efficient _iter slicing

### ISSUE THREAD

**Issue by seanmacavaney** [allenai/ir_datasets#26]
As @jacobdanovitch suggested in #25, there are some cases in which slicing of documents would be beneficial. In that case, workers in multiple processes are used to prepare data for a pytorch model in parallel. There are certainly other cases too, such as if you wanted a quick way to resume processing from a certain point.

(The same goes for all _iters: docs, queries, qrels, scoreddocs, docpairs, but for simplicity, I'll write this issue focusing on docs.)

An easy way to do this is with itertools.islice as follows:

```python
docs_iter = itertools.islice(dataset.docs_iter(), start, stop, step)
```

But this results in the following undesirable behaviors:
 - If start > 0, the iterator must traverse through all documents up to start. Even when the cost of building the doc tuples is low (e.g., MS-MARCO), it still requires reading the input file up to that point.
 - If step > 1, there's a similar problem as with start > 0: wasted processing time and IO for the skipped documents.
 - islice doesn't support negative indexing for start, stop, or step. (I'm not totally sure what the use case would be for this, but it's a limitation.)

I propose two changes to the API to facilitate more efficient slicing of documents. First, the addition of a `docs_count()` function that returns the total number of documents. Since in all datasets, the total number of documents is known ahead of time, this can be hard-coded. A fallback implementation can be provided for some types, like tsv, where counting the number of documents can be done with little compute (though potentially a lot of IO). A warning is probably warranted in this case, and the count should be cached for subsequent calls. (Maybe there should be an argument to disable IO for counts, if the consumer would only want a count if it's quick, e.g., `docs_count(no_io=True)`.) In other cases, docs_count() could raise a NotImplementedError, indicating that it is not available. Documentation could be updated to utilize docs_count(), when available. 

Second, the addition of a `docs_iter_slice(start=None, stop=None, step=None)` function that performs the slicing operations. In all cases, a default implementation could be provided that uses `islice` and `docs_iter()` (and `docs_count()` if negative). Implementations could then override this function to provide more efficient slicing, when available. For instance,  MS-MARCO could reduce the compute overhead by reading lines of the input file up to a certain index (skipping the somewhat more expensive work of preparing the doc tuple). Or trec-robust04 could count the number of </DOC> tags encountered, and use checkpoint files that indicate how many documents are in each source file.

Even more efficient implementations could take advantage of the zpickle docstore built for each dataset. Pointers could be built to positions in the zpickle file for each position. This would reduce most of the overhead, and could become the "preferred" way to handle documents in small collections.

**Comment by seanmacavaney** [comment]
Maybe it would be cool to be able to take advantage of the slice notation here? Could it look like: `dataset.docs_iter_slice[start:stop:step]`? I'm pretty sure this would need to be something that's set up in the constructor, like so:

```python
class SomeDocs(BaseDocs):
    def __init__(self):
        self.docs_iter_slice = SomeSlicer(self)
```

SomeSlicer would then expose a `__getitem__` function to handle the slicing. There could be pretty generic slicer implementations that, say, read in lines up to `start` and then fall back on islice for stop and step, or count the occurrences of a given pattern (e.g., `</DOC>`).

**Comment by jacobdanovitch** [comment]
1. Regarding `docs_count()`, especially given that this can be hard-coded, I definitely think that would be a useful addition. Maybe it could be built on creation if it's not already provided (I imagine you have to iterate through the collection at least once when it's being downloaded/processed).  That could have other uses as well (stuff like `tqdm(dataset.docs_iter(), total=dataset.docs_count())`, off the top of my head).

2. I'm not super familiar with zpickle (though clearly I should look into it given how well it works here), so my knowledge here is a bit limited, but I wonder if there would be any use cases for a more generic `Subset` functionality. For example, if I (for whatever dumb reason) want the 1st, 3rd, and 11th queries/documents, that wouldn't necessarily fit into the `islice`-style API.

```python
dataset = ir_datasets.load('msmarco-passage/dev')
subset = SubsetDocs(dataset)

every_fifth = subset[1:25:5]
some_docs = subset[[1,3,11]]
# etc
``` 

The default implementation could then use itertools if the input is a slice object, otherwise the wasted-io version. I imagine this would be pretty easy using your pointer idea:

> Pointers could be built to positions in the zpickle file for each position.

Doesn't the MsMarco document collection provide a file similar to this, of (doc_id, file_ptr) pairs? I think it makes a lot of sense as an approach. How difficult would it be to implement?

**Comment by seanmacavaney** [comment]
> Maybe it could be built on creation if it's not already provided

We already have them in the integration test files for each dataset. But building them on creation sounds like a good fallback.

> I imagine you have to iterate through the collection at least once when it's being downloaded/processed

Not always-- you can build a dataset object from arbitrary TSV files. In this case, we don't traverse them before they can be used. This allows easily plugging in whatever collection you like.

> I wonder if there would be any use cases for a more generic Subset functionality.

This seems like a good use for a wrapper, as you show. To me, it's elegant but it's a little unclear how useful it is to want specific indices, rather than specific doc_ids. I can see specifying index slices as reasonable (e.g., your multiprocessing issue), and specifying individual document IDs (already supported by docs_store()). But it seems like an odd situation to want _individual indices_.

If you don't mind loading all documents into memory, this sort of thing can be achieved easily by passing the docs_iter into a pandas dataframe.

>  Doesn't the MsMarco document collection provide a file similar to this? 

Oh cool, I never noticed that before. The file is here for future refernece: `https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-docs-lookup.tsv.gz`.

The zpickle implementation I have now for `docs_store()`s provides a different point on the space-time efficiency curve -- it's compressed so it takes up less space (but decompressing the doc takes a bit of time, #22 should improve further by using lz4 instead of zlib) but it's also faster to look up positions by using some mmap tricks (slash doesn't require loading the entire mapping file into memory).

Note to self: To support this type of index slicing, maybe it would be good to add the index of the document within each file to the ClueWeb09/12 checkpoint files. #1. It would be annoying to re-build all the checkpoints, but would allow this sort of functionality.

**Comment by seanmacavaney** [comment]
@jacobdanovitch aside from completeness, do you think there's a need for negative steps? This would be more complicated to handle because it would either mean going through the file backwards (or keeping it all in memory to return the reverse order). Both of these are not ideal and annoying.

**Comment by jacobdanovitch** [comment]
Sorry, just saw this. If wanting specific indices would add to the complexity then yeah, probably isn't worth it at all. Re: negative steps, I can't imagine a use case for that myself, it wouldn't happen in the pytorch scenario and there's no reason to have to iterate over the collections backwards or anything that I'm aware of.

**Comment by seanmacavaney** [comment]
Efficient iter slicing now in the clueweb12 branch.

I went with this approach, where the iterators themselves accept slices. Most implementations use the docstore (which now keeps track of doc indices -> positions in store file), and an efficient implementation also exists for datasets that use WARC files.

```
import ir_datasets
dataset = ir_datasets.load('clueweb12')
dataset.docs_iter()[500:1000] # normal slicing behavior
# WarcDoc(doc_id='clueweb12-0000tw-00-00502', ...), WarcDoc(doc_id='clueweb12-0000tw-00-00503', ...), ...
dataset.docs_iter()[-10:-8] # includes negative indexing
# WarcDoc(doc_id='clueweb12-1914wb-28-24245', ...), WarcDoc(doc_id='clueweb12-1914wb-28-24246', ...)
dataset.docs_iter()[::100] # includes support for skip (only positive values)
# WarcDoc(doc_id='clueweb12-0000tw-00-00000', ...), WarcDoc(doc_id='clueweb12-0000tw-00-00100', ...), ...
dataset.docs_iter()[1/3:2/3] # supports proportional slicing (this takes the middle third of the collection)
# WarcDoc(doc_id='clueweb12-0605wb-28-12714', ...), WarcDoc(doc_id='clueweb12-0605wb-28-12715', ...), ...
```

A few things to do before wrapping this up:

- [ ] What to do about `ir_datasets.create_dataset`? Does this work?
- [ ] Still want to add docs_count?
- [ ] Anything to do with queries/qrels/etc. iterators? I think I'm fine with just docs for now.
- [ ] Test on all datasets. (I think I missed GOV2 testing for the WARC files. Maybe others need testing too.)
