### ISSUE TITLE
Dependency on an outdated warc python module for ClueWeb12

### ISSUE THREAD

**Issue by Zendelo** [allenai/ir_datasets#268]
Trying to load and iterate over the CW12 collection results in an error.

**Affected dataset(s)**
ClueWeb12 (and probably other collections that depend on warc)

**To Reproduce**
```
import ir_datasets
dataset = ir_datasets.load("clueweb12")
dataset.docs_iter()[0]
```

> >>> dataset.docs_iter()[0]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/indices/clueweb_warc.py", line 247, in __getitem__
>     return next(new_it)
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/indices/clueweb_warc.py", line 214, in __next__
>     result = next(self.current_file)
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/formats/webarc.py", line 41, in _docs_ctxt_iter_warc
>     warc = self._docs_warc_lib()
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/formats/webarc.py", line 38, in _docs_warc_lib
>     return ir_datasets.lazy_libs.warc()
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/lazy_libs.py", line 62, in warc
>     import warc
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/warc/__init__.py", line 10, in <module>
>     from .arc import ARCFile, ARCRecord, ARCHeader
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/warc/arc.py", line 7, in <module>
>     import __builtin__
> ModuleNotFoundError: No module named '__builtin__'

**Expected behavior**
Expect to load the document

**Additional context**
The warc python module repo was last updated in 2012, so it's incompatible with Python 3.x.
Wonder if I've missed something, as it seems it hasn't been reported so far.

**Comment by Zendelo** [comment]
The initial bug is caused by having an old warc module installed (running `pip install warc`)
but without it, having warc3-wet installed (according to the requirements file) results with an error as well:

>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/ir_datasets/lazy_libs.py", line 62, in warc
>     import warc
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/warc/__init__.py", line 10, in <module>
>     from .arc import ARCFile, ARCRecord, ARCHeader
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/warc/arc.py", line 15, in <module>
>     from .utils import CaseInsensitiveDict
>   File "/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/site-packages/warc/utils.py", line 10, in <module>
>     from collections import MutableMapping, Mapping
> ImportError: cannot import name 'MutableMapping' from 'collections' (/home/sh3/S3806763/miniconda3/envs/llama/lib/python3.10/collections/__init__.py)

A workaround for that is to change the file warc/utils.py to import it from `collections.abc`. Though there perhaps might be a better solution.

**Comment by Zendelo** [comment]
I found these 2 pull requests asking to make the change:
[https://github.com/Willian-Zhang/warc3/pulls ](https://github.com/Willian-Zhang/warc3/pulls)
It seems they were ignored for a couple of years, so perhaps it's possible to change the dependency in the requirements file to a forked repo, which would be more up-to-date. For your consideration, anyway, feel free to close this one

**Comment by seanmacavaney** [comment]
Thanks @Zendelo! There's precedent for a forked repo already -- `warc3-wet-clueweb09>=0.2.5` contains fixes to specifically handle clueweb09 WARC files. https://github.com/seanmacavaney/warc3-clueweb

I don't really have the bandwidth right now to tackle this, but I'd be happy to take a PR for a `warc3-wet-clueweb12` that addresses these issues :)

**Comment by Zendelo** [comment]
Hey @seanmacavaney,
I've looked deeper into it; the only change needed is that one line in the warc utils.py file to import
from collections.abc instead of collections.

Changing it passes all the existing tests but one, the [HTML extractor](https://github.com/allenai/ir_datasets/blob/ce73e6a90fcc07aa20bf3d98375f60abbad1a525/test/integration/clueweb12.py#L26), which fails for two documents.
Documents 9 and 1000 are different, but the differences are only in the number of white spaces (and line terminators).

I emailed the original warc3 repo owner @Willian-Zhang, asking him to make the update.
Creating a new fork just for that change seems redundant, but I'll do it if I don't get a response in the next couple of weeks.

Regarding the failing test, I suggest updating the test as it seems to me that gives the expected result.
Or perhaps even consider a test that ignores whitespace.

**Comment by Willian-Zhang** [comment]
Request has been merged and released in 0.2.4, please check.

**Comment by Zendelo** [comment]
The updated warc3 module works, problem solved.
@Willian-Zhang thanks for the prompt response!

**Comment by seanmacavaney** [comment]
Thanks for bringing this to my attention!

Given that these dependencies are limited to the clueweb datasets, perhaps a fourth option would be to make them an optional dependency? I.e., have the end user manually install `warc3-wet` and `warc3-wet-clueweb09` if they want the clueweb functionality.

I think we want to move away from having these one-off dependencies anyway.

A fifth option might be to split out the clueweb functionality entirely into a separate GPL2-licensed extension package.

**Comment by Willian-Zhang** [comment]
Warc3-wet author here, I've got no problem with add a new license on my part.
