### ISSUE TITLE
Default Text BEIR

### ISSUE THREAD

**Issue by fschlatt** [allenai/ir_datasets#273]
**Is your feature request related to a problem? Please describe.**
Not all document corpora in the beir dataset have a `default_text`. In particular, [SciDoc](https://github.com/allenai/ir_datasets/blob/ce73e6a90fcc07aa20bf3d98375f60abbad1a525/ir_datasets/datasets/beir.py#L49) and [Touche](https://github.com/allenai/ir_datasets/blob/ce73e6a90fcc07aa20bf3d98375f60abbad1a525/ir_datasets/datasets/beir.py#L70). Is there a particular reason for this? It seems like for both cases, the title and text (as is the case for most beir documents) would be a sensible option. 

**Describe the solution you'd like**
Add `default_text` for all beir datasets

**Comment by seanmacavaney** [comment]
`ir_datasets==0.5.9` now addresses :)
