### ISSUE TITLE
download can silently fail?

### ISSUE THREAD

**Issue by seanmacavaney** [allenai/ir_datasets#55]
As reported by @yuhaia on MacOS Catalina 10.15.7 with Python 3.7 for `macavaney:anserini-trec-robust04`'s anserini index download. https://github.com/allenai/ir_datasets/issues/52#issuecomment-814020499

The best place to start would be to simulate a failed download on the same OS, python version, and dataset and see if I can reproduce it. If not, I'm not sure what to try next.

@yuhaia-- if there are any more details on this that could help me get to the bottom of this problem, please let me know!

**Comment by seanmacavaney** [comment]
In the same environment, @yuhaia also reports that downloads from TREC can also silently fail.

**Comment by seanmacavaney** [comment]
I believe that this was an issue related to previously buggy handling of TREC Robust (which has since been fixed). I'll close for now, but we can re-open if others report it after the fix.

**Comment by cakiki** [comment]
Hi @seanmacavaney! Figured a comment here would be better than opening a new issue. I seem to have encountered a similar issue of a silent fail with `robust04` where I can load the dataset (Same setup as the docs) but no actual docs are loaded.

I'm using `Ubuntu 20.04` (actually a docker container) and `Python 3.8.10` and `ir_datasets 0.5.0`

 I'm using the same exact version of the dataset Jimmy Lin provides the hash to [here]( https://github.com/osirrc/jig/issues/28#issue-430193728)

![image](https://user-images.githubusercontent.com/3664563/143873720-460aeb7b-8460-4ff8-a890-743d919a741d.png)

**Comment by seanmacavaney** [comment]
Thanks for reporting! Based on the md5s you linked to, this appears to be yet another format that the dataset is sometimes distributed as. We should be able to support all versions, but since I don't have this particular version, I may need your help along the way to test out fixes. I'll keep you posted.

Related to #60

**Comment by cakiki** [comment]
Sure thing; happy to help!

**Comment by seanmacavaney** [comment]
Hi @cakiki. I pushed a potential fix to the `robust04-fix` branch: https://github.com/allenai/ir_datasets/tree/robust04-fix. I verified that it worked on a re-compressed version of the corpus that I made, but it's important to see that it works on the data from the disks. The MD5s of this version don't match what was reported in the file you sent, but I suspect that's just due to differences in the compression settings.

Could you try running it on your copy of the `.z`-compressed data? You'll have to remove your `trec45.pklz4` first and install the `unlzw3` package [1] (in `requirements.txt`). This will test a few docs to make sure it gives the same results as the `.gz` version I have.

```bash
python -m test.integration.trec_robust04
```

Thanks again for the help!

[1] I went with the `unlzw3` package over the c-based `unlzw`, even though it's much slower. That's because of the concerns about the maintenance of the `unlzw` package expressed here: https://stackoverflow.com/questions/32921263/uncompressing-a-z-file-with-python. Once a docstore is built, the iteration is much faster, so it is potentially only a one-time upfront cost.

**Comment by cakiki** [comment]
Hi @seanmacavaney. I pip installed the branch with the fix, but I don't think it worked. I'm starting to wonder whether I'm doing anything wrong.

I'm happy to keep testing, but I could also send you files from the disks; or even the entire disk45 folder.

**Comment by cakiki** [comment]
```bash
Successfully built ir-datasets warc3-wet-clueweb09 unlzw3 cbor
Installing collected packages: cbor, trec-car-tools, lz4, warc3-wet, warc3-wet-clueweb09, zlib-state, ijson, pyautocorpus, unlzw3, ir-datasets
Successfully installed cbor-1.0.0 ijson-3.1.4 ir-datasets-0.5.0 lz4-3.1.10 pyautocorpus-0.1.6 trec-car-tools-2.5.4 unlzw3-0.2.1 warc3-wet-0.2.3 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.3
WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
root@f535407a1f28:/ir_datasets# python -m test.integration.trec_robust04
trec-robust04 docs: 0doc [01:17, ?doc/s]
[INFO] [finished] trec-robust04 docs: [01:17] [0doc] [?doc/s]
[INFO] [starting] doc lookups by index
[INFO] [starting] building docstore
docs_iter:   0%|                                    | 0/528155 [01:15<?, ?doc/s]
[INFO] [finished] docs_iter: [01:15] [0doc] [?doc/s]
[INFO] [finished] building docstore [01:16]
[INFO] [error] doc lookups by index [01:16]
[INFO] [starting] doc lookups by doc_id
[INFO] [starting] building docstore
docs_iter:   0%|                                    | 0/528155 [01:17<?, ?doc/s]
[INFO] [finished] docs_iter: [01:17] [0doc] [?doc/s]
[INFO] [finished] building docstore [01:17]
[INFO] [error] doc lookups by doc_id [01:17]
[INFO] Please confirm you agree to the TREC Robust 2004 data usage agreement found at <https://trec.nist.gov/data/cd45/index.html>
[INFO] If you have a local copy of https://trec.nist.gov/data/robust/qrels.robust2004.txt, you can symlink it here to avoid downloading it again: /tf/data/external/IR_DATASETS/downloads/123c2a0ba2ec31178cb1050995dcfdfa
[INFO] [starting] https://trec.nist.gov/data/robust/qrels.robust2004.txt
[INFO] [finished] https://trec.nist.gov/data/robust/qrels.robust2004.txt: [00:01] [6.54MB] [5.77MB/s]
trec-robust04 qrels: 311410qrel [00:03, 96275.73qrel/s]                                           
[INFO] [finished] trec-robust04 qrels: [00:03] [311410qrel] [96274.20qrel/s]       
trec-robust04/fold1 qrels: 62789qrel [00:01, 57460.09qrel/s]
[INFO] [finished] trec-robust04/fold1 qrels: [00:01] [62789qrel] [57457.44qrel/s]
trec-robust04/fold2 qrels: 63917qrel [00:01, 57797.58qrel/s]
[INFO] [finished] trec-robust04/fold2 qrels: [00:01] [63917qrel] [57794.48qrel/s]
trec-robust04/fold3 qrels: 62901qrel [00:01, 57734.98qrel/s]
[INFO] [finished] trec-robust04/fold3 qrels: [00:01] [62901qrel] [57732.31qrel/s]
trec-robust04/fold4 qrels: 57962qrel [00:01, 52777.53qrel/s]
[INFO] [finished] trec-robust04/fold4 qrels: [00:01] [57962qrel] [52774.37qrel/s]
trec-robust04/fold5 qrels: 63841qrel [00:01, 58219.68qrel/s]
[INFO] [finished] trec-robust04/fold5 qrels: [00:01] [63841qrel] [58217.09qrel/s]
[INFO] [starting] https://trec.nist.gov/data/robust/04.testset.gz
[INFO] [finished] https://trec.nist.gov/data/robust/04.testset.gz: [00:00] [34.3kB] [309kB/s]
trec-robust04 queries: 250query [00:00, 395.46query/s]                                     
[INFO] [finished] trec-robust04 queries: [00:00] [250query] [395.42query/s]
trec-robust04/fold1 queries: 50query [00:00, 1514.23query/s]
[INFO] [finished] trec-robust04/fold1 queries: [00:00] [50query] [1511.82query/s]
trec-robust04/fold2 queries: 50query [00:00, 1509.87query/s]
[INFO] [finished] trec-robust04/fold2 queries: [00:00] [50query] [1507.54query/s]
trec-robust04/fold3 queries: 50query [00:00, 1508.60query/s]
[INFO] [finished] trec-robust04/fold3 queries: [00:00] [50query] [1506.40query/s]
trec-robust04/fold4 queries: 50query [00:00, 1504.80query/s]
[INFO] [finished] trec-robust04/fold4 queries: [00:00] [50query] [1502.66query/s]
trec-robust04/fold5 queries: 50query [00:00, 1503.55query/s]
[INFO] [finished] trec-robust04/fold5 queries: [00:00] [50query] [1501.43query/s]
.
======================================================================
ERROR: test_trec_robust04_docs (__main__.TestTrecRobust04) [docs_iter split] (dataset='trec-robust04')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ir_datasets/test/integration/base.py", line 38, in _test_docs
    self._assert_namedtuple(next(it[idx:idx+1]), doc)
  File "/ir_datasets/ir_datasets/indices/lz4_pickle.py", line 54, in __next__
    raise StopIteration
StopIteration

======================================================================
ERROR: test_trec_robust04_docs (__main__.TestTrecRobust04) [docs_store] (dataset='trec-robust04')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ir_datasets/test/integration/base.py", line 46, in _test_docs
    ret_doc = doc_store.get(doc.doc_id)
  File "/ir_datasets/ir_datasets/indices/base.py", line 13, in get
    raise KeyError(f'doc_id={doc_id} not found')
KeyError: 'doc_id=FBIS3-1 not found'

======================================================================
FAIL: test_trec_robust04_docs (__main__.TestTrecRobust04) [docs] (dataset='trec-robust04')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ir_datasets/test/integration/base.py", line 29, in _test_docs
    self.assertEqual(expected_count, count)
AssertionError: 528155 != 0

----------------------------------------------------------------------
Ran 3 tests in 239.856s

FAILED (failures=1, errors=2)
```

**Comment by seanmacavaney** [comment]
Thanks! Judging from the output, it seems like it's found the files but still isn't applying the decompression properly. By chance, are the `.z` file extensions in uppercase? If so, I've pushed a chance that will address that.

If not, could you send me the output of `find ~/.ir_datasets/trec-robust04/trec45/` (or just some sample lines from it)?

Thanks!

**Comment by cakiki** [comment]
They are indeed uppercase! I'll give it another go with the most recent change you pushed to the robust04 branch.

**Comment by cakiki** [comment]
The newest fix does indeed work!
```bash
root@32c432cd2d52:/ir_datasets# python -m test.integration.trec_robust04
trec-robust04 docs: 528155doc [00:04, 115252.55doc/s]
[INFO] [finished] trec-robust04 docs: [00:04] [528155doc] [115250.72doc/s]
[INFO] [starting] doc lookups by index
[INFO] [finished] doc lookups by index [15ms]
[INFO] [starting] doc lookups by doc_id
[INFO] [finished] doc lookups by doc_id [1ms]
trec-robust04 qrels: 311410qrel [00:01, 273996.57qrel/s]
[INFO] [finished] trec-robust04 qrels: [00:01] [311410qrel] [273985.93qrel/s]
trec-robust04/fold1 qrels: 62789qrel [00:01, 58505.60qrel/s]
[INFO] [finished] trec-robust04/fold1 qrels: [00:01] [62789qrel] [58503.19qrel/s]
trec-robust04/fold2 qrels: 63917qrel [00:01, 59287.29qrel/s]
[INFO] [finished] trec-robust04/fold2 qrels: [00:01] [63917qrel] [59284.97qrel/s]
trec-robust04/fold3 qrels: 62901qrel [00:01, 58342.43qrel/s]
[INFO] [finished] trec-robust04/fold3 qrels: [00:01] [62901qrel] [58339.83qrel/s]
trec-robust04/fold4 qrels: 57962qrel [00:01, 53938.70qrel/s]
[INFO] [finished] trec-robust04/fold4 qrels: [00:01] [57962qrel] [53936.20qrel/s]
trec-robust04/fold5 qrels: 63841qrel [00:01, 59561.41qrel/s]
[INFO] [finished] trec-robust04/fold5 qrels: [00:01] [63841qrel] [59559.17qrel/s]
trec-robust04 queries: 250query [00:00, 4486.67query/s]
[INFO] [finished] trec-robust04 queries: [00:00] [250query] [4482.17query/s]
trec-robust04/fold1 queries: 50query [00:00, 1461.77query/s]
[INFO] [finished] trec-robust04/fold1 queries: [00:00] [50query] [1459.63query/s]
trec-robust04/fold2 queries: 50query [00:00, 1505.39query/s]
[INFO] [finished] trec-robust04/fold2 queries: [00:00] [50query] [1503.21query/s]
trec-robust04/fold3 queries: 50query [00:00, 1540.91query/s]
[INFO] [finished] trec-robust04/fold3 queries: [00:00] [50query] [1538.66query/s]
trec-robust04/fold4 queries: 50query [00:00, 1527.09query/s]
[INFO] [finished] trec-robust04/fold4 queries: [00:00] [50query] [1524.08query/s]
trec-robust04/fold5 queries: 50query [00:00, 1512.74query/s]
[INFO] [finished] trec-robust04/fold5 queries: [00:00] [50query] [1510.66query/s]
.
----------------------------------------------------------------------
Ran 3 tests in 11.436s

OK
```


![image](https://user-images.githubusercontent.com/3664563/144744864-e33e90e5-7dbf-4fda-917b-7b0af455bd5b.png)

**Comment by cakiki** [comment]
Follow up question before you close the issue: how come the first command in cell 2 of the notebook does not build the docstore, while the second does?

**Comment by seanmacavaney** [comment]
The idea is to not create the docstore unless it's necessary to reduce storage overhead.  For a simple, in-sequence iteration over a corpus (a really common operation, e.g., for indexing), a docstore usually isn't needed*. But in most datasets, you cannot efficiently jump ahead, so a docstore (containing document index offset info) is built when the user slices the iterator. In the case you show, it isn't strictly necessary since the slice doesn't jump ahead and has no stride. But right now, it doesn't distinguish different slicing behaviours to conditionally trigger the creation of a docstore.

\* There are exceptions to this rule, particularly when iteration cannot be done efficiently. This is a decision that I've been making on a case-by-case basis. I'm totally open to changing the behaviour for robust04, given that it's a bit expensive to parse the corpus and the docstore doesn't add very much storage overhead (~1.2GB).

There are probably other optimisations I could make to speed up the parsing of robust04 too, though, that would avoid the docstore overhead for simple iterations. The gzip-encoded version iterates about twice as fast as the `.z`-encoded files. But it's still not super efficient, mostly because it's using bs4 to handle xml-like tags and such. I've been working on some improvements for HTML parsing (#64), and that should be applicable here as well.
