### ISSUE TITLE
documentation on how to add new datasets

### ISSUE THREAD

**Issue by cmacdonald** [allenai/ir_datasets#56]
**Describe the proposed change**

documentation on how to add new datasets would benefit the amount of work you need to do Sean.

**Comment by cmacdonald** [comment]
The link doesnt yet appear on ir-datasets.com

**Comment by seanmacavaney** [comment]
It's on the [master version of the documentation](https://ir-datasets.com/master/) for now; it'll get pushed out with the next release (which should be soon)
