### ISSUE TITLE
dataset counts

### ISSUE THREAD

**Issue by seanmacavaney** [allenai/ir_datasets#66]
**Is your feature request related to a problem? Please describe.**

I often find myself looking up dataset characteristics from the tests (e.g., number of documents, queries, qrels in a dataset, for instance). It would be nice if this information was more easily accessible.

**Describe the solution you'd like**

Have a structured store of counts of different entity types for each dataset. Make this information available both on the documentation page for each dataset and on a summary page.

**Describe alternatives you've considered**

Could also be handled by more consistent standards for manually documenting the datasets. But I think I'd rather have this information automatically generated and easily accessible in a machine-readable format.

**Additional context**

(none)

**Comment by bpiwowar** [comment]
I think it would be quite valuable to have meta-information about each data piece. In `datamaestro`, this is enforce by having each dataset associated with a `Data` object, which is basically a generic object that can be specialized (by subclassing), allowing to access meta-information about the dataset.


For instance, an excerpt including document count would be

```py3
class AdhocDocuments(Base):
    """A set of documents with identifiers
    
    Attributes:
    
    count: number of documents or passages
    """

    count: Option[Optional[int]]


class Adhoc(Base):
    """An Adhoc IR collection made of documents, topics and assessments"""

    documents: Param[AdhocDocuments]
    topics: Param[AdhocTopics]
    assessments: Param[AdhocAssessments]

```

**Comment by seanmacavaney** [comment]
What sorts of other meta-information have you found to be useful? There's already attributes like `.docs_count()`, `docs_lang()` and `qrels_defs()` for every provider (different attributes enforced on different entity types). Though most of this information is hard-coded (i.e., the meanings of the different relevance levels doesn't change), th main annoyance now is that `.docs_count()` comes from the data itself, rather than being hard-coded.

#85 added "count_hint"s in some cases, to allow for more informative progress bars, though these are not exposed via the official API.

**Comment by bpiwowar** [comment]
After looking at the code, it seems I can infer from the handlers and various other methods the underlying information I need - not really practical since each time I have to look at the code, but otherwise no real complaint...

**Comment by seanmacavaney** [comment]
Would documentation about the `*_provider` methods help?

**Comment by bpiwowar** [comment]
do you mean `*_handler`? I don't see any `*_provider` method.

**Comment by seanmacavaney** [comment]
Ah, yup. That's what I meant.

**Comment by seanmacavaney** [comment]
Maybe these cases could be shown with a new symbole in the catalog as well? Like so:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/2607830/126156614-1f6ce176-9b47-449c-becd-788de5e9ad63.png">

**Comment by bpiwowar** [comment]
> Maybe these cases could be shown with a new symbole in the catalog as well? Like so:
> 
> <img alt="image" width="530" src="https://user-images.githubusercontent.com/2607830/126156614-1f6ce176-9b47-449c-becd-788de5e9ad63.png">

Looks more like issue #91, but yes good idea

**Comment by seanmacavaney** [comment]
One other possible meta-information: I stumbled upon a feature I forgot about: `*_hash`: https://github.com/allenai/ir_datasets/blob/master/ir_datasets/formats/base.py#L180. The intention was to have the hashes available somewhere to (1) allow users to verify that the processing done on their machines was identical to somebody else's, even across versions, and (2) help identify regressions across versions.
