### ISSUE TITLE
provide mulitple use examples

### ISSUE THREAD

**Issue by cmacdonald** [allenai/ir_datasets#73]
**Describe the proposed change**

![image](https://user-images.githubusercontent.com/620938/120885916-51780400-c5e3-11eb-8ec5-271aa57dbfc5.png)

Could this block have tabs, and others platforms could be shown too?

**Comment by seanmacavaney** [comment]
Great idea! I added PyTerrier examples for:
 - indexing, under `docs`
 - retrieval, under `queries`
 - experimentation, under `qrels`

There's several caveats for these auto-generated examples:
 1. Some doc fields do not make much sense to index. I filtered down to only text fields, and I removed `doc_id` and a few other fields I spotted that could be particularly problematic. But more attention may be needed on these in the future.
 2. I do not include examples for non-English docs or non-English queries
 3. Some datasets, like the ClueWebs and GOV2 currently need a wrapper to extract the HTML content. This will be improved in #72. Might want to re-visit (1) at that time as well.
 4. I did not include examples for scoreddocs and docpairs for pyterrier, as these are not directly supported at this time.

The interface changes *all* example tabs and remembers your selection across pages. Needed to do a bit of work to keep the page from jumping around too much when the user changes the example tabs.

I also took the opportunity to give examples for the CLI as well.
