### ISSUE TITLE
WaPost v4

### ISSUE THREAD

**Issue by gbennett71** [allenai/ir_datasets#90]
**Dataset Information:**

WaPost collection, as used in TREC News Track 2018, 2019, 2020, 2021

![image](https://user-images.githubusercontent.com/4514795/125582474-1cae5578-8027-4ad5-8820-2c75a0a19847.jpeg)

**Links to Resources:**

https://trec.nist.gov/data/wapost/

http://trec-news.org

https://www.nist.gov/publications/trec-2020-news-track-overview

https://trec.nist.gov/data/news2018.html (contains links for topics, relevance judgments for background linking and entity ranking tasks).

**Dataset ID(s):**

<propose dataset ID(s), and where they fit in the hierarchy>

**Supported Entities**

 - [x] docs
 - [x] queries
 - [x] qrels
 - [] scoreddocs
 - [] docpairs

**Additional comments/concerns/ideas/etc.**

**Comment by seanmacavaney** [comment]
Hi @gbennett71

Thanks for opening this issue and offering to help!

 - Do you know if the format of the files are the same in v3 & v4 as they are in v2?
 - If I provided a branch that added v3 and v4 integrations, would you be willing to run some tests I provide on the data to make sure the data processes correctly?
 - What are the md5 hashes of the v3 and v4 datasets? (i.e., the result of `md5sum WashingtonPost.v3.tar.gz WashingtonPost.v4.tar.gz`?

Thanks!
sean

**Comment by cmacdonald** [comment]
Sean, we have a copy. I'll ping you the location
