### ISSUE TITLE
Unique ID for each piece of data

### ISSUE THREAD

**Issue by bpiwowar** [allenai/ir_datasets#91]
**Is your feature request related to a problem? Please describe.**

There is no identifier for each piece of data, which hinders automation for packages using `ir_datasets`. For instance, the document collection in `cord19/trec-covid/round1` and `cord19/trec-covid/round2` is the same, but it is difficult to know whether it is the same or not.

**Describe the solution you'd like**

Assign a unique ID to each dataset part (documents, queries, etc.)

**Describe alternatives you've considered**

Testing whether the returned object is the same or not, generating a new ID. But if something changes between two runs (e.g. order of the iteration), this is broken. Another possibility would be to use the path of the data, but in the current implementation this triggers downloading the data.

**Additional context**

Trying to wrap `ir-datasets` as a  [datamaestro](https://github.com/experimaestro/datamaestro) module. In `datamaestro`, each piece of data is uniquely identified by an ID. This then would allow e.g. to index a collection when needed (rather than indexing n times the same one).

**Comment by seanmacavaney** [comment]
I think [`ir_datasets.corpus_id`](https://github.com/allenai/ir_datasets/blob/master/ir_datasets/__init__.py#L18) would solve the example you give? It only works for docs and when they share a parent in the hierarchy, but that assumption always holds with the current catalog. (And if it were not to hold, `ir_datasets.corpus_id` is written such that it would handle a list of exceptions.) Queries/qrels/etc. are rarely reused between datasets in their exact same form. And when they are, they either are dependent on the other entities (e.g., qrels are reused for the `*/judged` datasets, but the queries are filtered), or they are small enough that they don't actually add all that much overhead to recompute.

You could also check to see if the `.docs_handler()`, `.queries_handler()`, `.qrels_handler()`, etc. of two datasets are the same. (This is exactly what `ir_datasets.corpus_id` does.) As far as I'm aware, the code always reuses the handlers when the contents are the same.

**Comment by bpiwowar** [comment]
Yes this indeed solves my problem - would be better to have some way to enforce that, but I think you can close the issue for now.
