### ISSUE TITLE
Updated Fever dataset in BEIR

### ISSUE THREAD

**Issue by NThakur20** [allenai/ir_datasets#97]
Hi @seanmacavaney,

Just wanted to give a heads up that there were issues with the FEVER training qrels doc-ids containing special characters that were not present within the corpus. I have updated these doc-ids with the correct special characters.

Location of new FEVER dataset: ``https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fever.zip``

So, only changes are done to the ``qrels/train.tsv`` of ``fever.zip``.

Old ``fever.zip`` md5hash: ``88591ef8eb2913126d0c93ecbde6285f``
New ``fever.zip`` md5hash: ``5a818580227bfb4b35bb6fa46d9b6c03``

I didn't want to create a new version for this, as it will create confusion since there are no changes compared to the previous version. 

Let me know in case something else is required!

Thanks,
Nandan

**Comment by seanmacavaney** [comment]
Awesome- thanks. I just pushed an update for the new file.
